#
# TABLE STRUCTURE FOR: master_city
#

DROP TABLE IF EXISTS master_city;

CREATE TABLE `master_city` (
  `city_id` int(4) NOT NULL AUTO_INCREMENT,
  `city_name` varchar(100) DEFAULT NULL,
  `city_state_id` int(4) DEFAULT NULL,
  PRIMARY KEY (`city_id`)
) ENGINE=MyISAM AUTO_INCREMENT=12314 DEFAULT CHARSET=latin1;

INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (1, 'Kabupaten Aceh Barat', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (2, 'Kabupaten Aceh Barat Daya', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (3, 'Kabupaten Aceh Besar', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (4, 'Kabupaten Aceh Jaya', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (5, 'Kabupaten Aceh Selatan', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (6, 'Kabupaten Aceh Singkil', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (7, 'Kabupaten Aceh Tamiang', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (8, 'Kabupaten Aceh Tengah', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (9, 'Kabupaten Aceh Tenggara', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (10, 'Kabupaten Aceh Timur', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (11, 'Kabupaten Aceh Utara', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (12, 'Kabupaten Bener Meriah', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (13, 'Kabupaten Bireuen', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (14, 'Kabupaten Gayo Luwes', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (15, 'Kabupaten Nagan Raya', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (16, 'Kabupaten Pidie', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (17, 'Kabupaten Pidie Jaya', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (18, 'Kabupaten Simeulue', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (19, 'Kota Banda Aceh', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (20, 'Kota Langsa', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (21, 'Kota Lhokseumawe', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (22, 'Kota Sabang', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (23, 'Kota Subulussalam', 1);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (24, 'Kabupaten Asahan', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (25, 'Kabupaten Batubara', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (26, 'Kabupaten Dairi', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (27, 'Kabupaten Deli Serdang', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (28, 'Kabupaten Humbang Hasundutan', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (29, 'Kabupaten Karo', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (30, 'Kabupaten Labuhan Batu', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (31, 'Kabupaten Labuhanbatu Selatan', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (32, 'Kabupaten Labuhanbatu Utara', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (33, 'Kabupaten Langkat', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (34, 'Kabupaten Mandailing Natal', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (35, 'Kabupaten Nias', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (36, 'Kabupaten Nias Barat', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (37, 'Kabupaten Nias Selatan', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (38, 'Kabupaten Nias Utara', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (39, 'Kabupaten Padang Lawas', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (40, 'Kabupaten Padang Lawas Utara', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (41, 'Kabupaten Pakpak Barat', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (42, 'Kabupaten Samosir', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (43, 'Kabupaten Serdang Bedagai', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (44, 'Kabupaten Simalungun', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (45, 'Kabupaten Tapanuli Selatan', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (46, 'Kabupaten Tapanuli Tengah', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (47, 'Kabupaten Tapanuli Utara', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (48, 'Kabupaten Toba Samosir', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (49, 'Kota Binjai', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (50, 'Kota Gunung Sitoli', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (51, 'Kota Medan', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (52, 'Kota Padangsidempuan', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (53, 'Kota Pematang Siantar', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (54, 'Kota Sibolga', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (55, 'Kota Tanjung Balai', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (56, 'Kota Tebing Tinggi', 2);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (57, 'Kabupaten Agam', 3);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (58, 'Kabupaten Dharmas Raya', 3);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (59, 'Kabupaten Kepulauan Mentawai', 3);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (60, 'Kabupaten Lima Puluh Kota', 3);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (61, 'Kabupaten Padang Pariaman', 3);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (62, 'Kabupaten Pasaman', 3);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (63, 'Kabupaten Pasaman Barat', 3);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (64, 'Kabupaten Pesisir Selatan', 3);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (65, 'Kabupaten Sijunjung', 3);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (66, 'Kabupaten Solok', 3);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (67, 'Kabupaten Solok Selatan', 3);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (68, 'Kabupaten Tanah Datar', 3);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (69, 'Kota Bukittinggi', 3);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (70, 'Kota Padang', 3);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (71, 'Kota Padang Panjang', 3);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (72, 'Kota Pariaman', 3);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (73, 'Kota Payakumbuh', 3);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (74, 'Kota Sawah Lunto', 3);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (75, 'Kota Solok', 3);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (76, 'Kabupaten Bengkalis', 4);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (77, 'Kabupaten Indragiri Hilir', 4);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (78, 'Kabupaten Indragiri Hulu', 4);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (79, 'Kabupaten Kampar', 4);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (80, 'Kabupaten Kuantan Singingi', 4);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (81, 'Kabupaten Meranti', 4);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (82, 'Kabupaten Pelalawan', 4);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (83, 'Kabupaten Rokan Hilir', 4);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (84, 'Kabupaten Rokan Hulu', 4);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (85, 'Kabupaten Siak', 4);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (86, 'Kota Dumai', 4);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (87, 'Kota Pekanbaru', 4);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (88, 'Kabupaten Bintan', 5);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (89, 'Kabupaten Karimun', 5);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (90, 'Kabupaten Kepulauan Anambas', 5);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (91, 'Kabupaten Lingga', 5);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (92, 'Kabupaten Natuna', 5);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (93, 'Kota Batam', 5);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (94, 'Kota Tanjung Pinang', 5);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (95, 'Kabupaten Bangka', 6);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (96, 'Kabupaten Bangka Barat', 6);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (97, 'Kabupaten Bangka Selatan', 6);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (98, 'Kabupaten Bangka Tengah', 6);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (99, 'Kabupaten Belitung', 6);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (100, 'Kabupaten Belitung Timur', 6);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (101, 'Kota Pangkal Pinang', 6);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (102, 'Kabupaten Kerinci', 7);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (103, 'Kabupaten Merangin', 7);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (104, 'Kabupaten Sarolangun', 7);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (105, 'Kabupaten Batang Hari', 7);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (106, 'Kabupaten Muaro Jambi', 7);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (107, 'Kabupaten Tanjung Jabung Timur', 7);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (108, 'Kabupaten Tanjung Jabung Barat', 7);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (109, 'Kabupaten Tebo', 7);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (110, 'Kabupaten Bungo', 7);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (111, 'Kota Jambi', 7);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (112, 'Kota Sungai Penuh', 7);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (113, 'Kabupaten Bengkulu Selatan', 8);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (114, 'Kabupaten Bengkulu Tengah', 8);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (115, 'Kabupaten Bengkulu Utara', 8);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (116, 'Kabupaten Kaur', 8);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (117, 'Kabupaten Kepahiang', 8);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (118, 'Kabupaten Lebong', 8);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (119, 'Kabupaten Mukomuko', 8);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (120, 'Kabupaten Rejang Lebong', 8);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (121, 'Kabupaten Seluma', 8);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (122, 'Kota Bengkulu', 8);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (123, 'Kabupaten Banyuasin', 9);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (124, 'Kabupaten Empat Lawang', 9);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (125, 'Kabupaten Lahat', 9);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (126, 'Kabupaten Muara Enim', 9);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (127, 'Kabupaten Musi Banyu Asin', 9);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (128, 'Kabupaten Musi Rawas', 9);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (129, 'Kabupaten Ogan Ilir', 9);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (130, 'Kabupaten Ogan Komering Ilir', 9);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (131, 'Kabupaten Ogan Komering Ulu', 9);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (132, 'Kabupaten Ogan Komering Ulu Selatan', 9);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (133, 'Kabupaten Ogan Komering Ulu Timur', 9);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (134, 'Kota Lubuklinggau', 9);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (135, 'Kota Pagar Alam', 9);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (136, 'Kota Palembang', 9);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (137, 'Kota Prabumulih', 9);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (138, 'Kabupaten Lampung Barat', 10);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (139, 'Kabupaten Lampung Selatan', 10);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (140, 'Kabupaten Lampung Tengah', 10);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (141, 'Kabupaten Lampung Timur', 10);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (142, 'Kabupaten Lampung Utara', 10);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (143, 'Kabupaten Mesuji', 10);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (144, 'Kabupaten Pesawaran', 10);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (145, 'Kabupaten Pringsewu', 10);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (146, 'Kabupaten Tanggamus', 10);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (147, 'Kabupaten Tulang Bawang', 10);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (148, 'Kabupaten Tulang Bawang Barat', 10);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (149, 'Kabupaten Way Kanan', 10);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (150, 'Kota Bandar Lampung', 10);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (151, 'Kota Metro', 10);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (152, 'Kabupaten Lebak', 11);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (153, 'Kabupaten Pandeglang', 11);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (154, 'Kabupaten Serang', 11);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (155, 'Kabupaten Tangerang', 11);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (156, 'Kota Cilegon', 11);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (157, 'Kota Serang', 11);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (158, 'Kota Tangerang', 11);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (159, 'Kota Tangerang Selatan', 11);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (160, 'Kabupaten Adm. Kepulauan Seribu', 12);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (161, 'Kota Jakarta Barat', 12);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (162, 'Kota Jakarta Pusat', 12);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (163, 'Kota Jakarta Selatan', 12);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (164, 'Kota Jakarta Timur', 12);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (165, 'Kota Jakarta Utara', 12);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (166, 'Kabupaten Bandung', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (167, 'Kabupaten Bandung Barat', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (168, 'Kabupaten Bekasi', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (169, 'Kabupaten Bogor', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (170, 'Kabupaten Ciamis', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (171, 'Kabupaten Cianjur', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (172, 'Kabupaten Cirebon', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (173, 'Kabupaten Garut', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (174, 'Kabupaten Indramayu', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (175, 'Kabupaten Karawang', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (176, 'Kabupaten Kuningan', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (177, 'Kabupaten Majalengka', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (178, 'Kabupaten Purwakarta', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (179, 'Kabupaten Subang', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (180, 'Kabupaten Sukabumi', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (181, 'Kabupaten Sumedang', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (182, 'Kabupaten Tasikmalaya', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (183, 'Kota Bandung', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (184, 'Kota Banjar', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (185, 'Kota Bekasi', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (186, 'Kota Bogor', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (187, 'Kota Cimahi', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (188, 'Kota Cirebon', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (189, 'Kota Depok', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (190, 'Kota Sukabumi', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (191, 'Kota Tasikmalaya', 13);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (192, 'Kabupaten Banjarnegara', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (193, 'Kabupaten Banyumas', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (194, 'Kabupaten Batang', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (195, 'Kabupaten Blora', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (196, 'Kabupaten Boyolali', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (197, 'Kabupaten Brebes', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (198, 'Kabupaten Cilacap', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (199, 'Kabupaten Demak', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (200, 'Kabupaten Grobogan', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (201, 'Kabupaten Jepara', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (202, 'Kabupaten Karanganyar', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (203, 'Kabupaten Kebumen', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (204, 'Kabupaten Kendal', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (205, 'Kabupaten Klaten', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (206, 'Kabupaten Kota Tegal', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (207, 'Kabupaten Kudus', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (208, 'Kabupaten Magelang', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (209, 'Kabupaten Pati', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (210, 'Kabupaten Pekalongan', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (211, 'Kabupaten Pemalang', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (212, 'Kabupaten Purbalingga', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (213, 'Kabupaten Purworejo', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (214, 'Kabupaten Rembang', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (215, 'Kabupaten Semarang', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (216, 'Kabupaten Sragen', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (217, 'Kabupaten Sukoharjo', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (218, 'Kabupaten Temanggung', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (219, 'Kabupaten Wonogiri', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (220, 'Kabupaten Wonosobo', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (221, 'Kota Magelang', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (222, 'Kota Pekalongan', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (223, 'Kota Salatiga', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (224, 'Kota Semarang', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (225, 'Kota Surakarta', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (226, 'Kota Tegal', 14);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (227, 'Kabupaten Bantul', 15);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (228, 'Kabupaten Gunung Kidul', 15);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (229, 'Kabupaten Kulon Progo', 15);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (230, 'Kabupaten Sleman', 15);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (231, 'Kota Yogyakarta', 15);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (232, 'Kabupaten Bangkalan', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (233, 'Kabupaten Banyuwangi', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (234, 'Kabupaten Blitar', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (235, 'Kabupaten Bojonegoro', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (236, 'Kabupaten Bondowoso', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (237, 'Kabupaten Gresik', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (238, 'Kabupaten Jember', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (239, 'Kabupaten Jombang', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (240, 'Kabupaten Kediri', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (241, 'Kabupaten Lamongan', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (242, 'Kabupaten Lumajang', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (243, 'Kabupaten Madiun', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (244, 'Kabupaten Magetan', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (245, 'Kabupaten Malang', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (246, 'Kabupaten Mojokerto', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (247, 'Kabupaten Nganjuk', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (248, 'Kabupaten Ngawi', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (249, 'Kabupaten Pacitan', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (250, 'Kabupaten Pamekasan', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (251, 'Kabupaten Pasuruan', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (252, 'Kabupaten Ponorogo', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (253, 'Kabupaten Probolinggo', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (254, 'Kabupaten Sampang', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (255, 'Kabupaten Sidoarjo', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (256, 'Kabupaten Situbondo', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (257, 'Kabupaten Sumenep', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (258, 'Kabupaten Trenggalek', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (259, 'Kabupaten Tuban', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (260, 'Kabupaten Tulungagung', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (261, 'Kota Batu', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (262, 'Kota Blitar', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (263, 'Kota Kediri', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (264, 'Kota Madiun', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (265, 'Kota Malang', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (266, 'Kota Mojokerto', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (267, 'Kota Pasuruan', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (268, 'Kota Probolinggo', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (269, 'Kota Surabaya', 16);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (270, 'Kabupaten Badung', 17);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (271, 'Kabupaten Bangli', 17);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (272, 'Kabupaten Buleleng', 17);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (273, 'Kabupaten Gianyar', 17);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (274, 'Kabupaten Jembrana', 17);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (275, 'Kabupaten Karang Asem', 17);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (276, 'Kabupaten Klungkung', 17);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (277, 'Kabupaten Tabanan', 17);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (278, 'Kota Denpasar', 17);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (279, 'Kabupaten Bima', 18);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (280, 'Kabupaten Dompu', 18);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (281, 'Kabupaten Lombok Barat', 18);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (282, 'Kabupaten Lombok Tengah', 18);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (283, 'Kabupaten Lombok Timur', 18);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (284, 'Kabupaten Lombok Utara', 18);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (285, 'Kabupaten Sumbawa', 18);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (286, 'Kabupaten Sumbawa Barat', 18);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (287, 'Kota Bima', 18);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (288, 'Kota Mataram', 18);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (289, 'Kabupaten Alor', 19);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (290, 'Kabupaten Belu', 19);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (291, 'Kabupaten Ende', 19);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (292, 'Kabupaten Flores Timur', 19);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (293, 'Kabupaten Kupang', 19);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (294, 'Kabupaten Lembata', 19);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (295, 'Kabupaten Manggarai', 19);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (296, 'Kabupaten Manggarai Barat', 19);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (297, 'Kabupaten Manggarai Timur', 19);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (298, 'Kabupaten Nagekeo', 19);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (299, 'Kabupaten Ngada', 19);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (300, 'Kabupaten Rote Ndao', 19);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (301, 'Kabupaten Sabu Raijua', 19);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (302, 'Kabupaten Sikka', 19);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (303, 'Kabupaten Sumba Barat', 19);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (304, 'Kabupaten Sumba Barat Daya', 19);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (305, 'Kabupaten Sumba Tengah', 19);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (306, 'Kabupaten Sumba Timur', 19);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (307, 'Kabupaten Timor Tengah Selatan', 19);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (308, 'Kabupaten Timor Tengah Utara', 19);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (309, 'Kota Kupang', 19);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (310, 'Kabupaten Bengkayang', 20);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (311, 'Kabupaten Kapuas Hulu', 20);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (312, 'Kabupaten Kayong Utara', 20);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (313, 'Kabupaten Ketapang', 20);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (314, 'Kabupaten Kubu Raya', 20);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (315, 'Kabupaten Landak', 20);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (316, 'Kabupaten Melawi', 20);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (317, 'Kabupaten Pontianak', 20);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (318, 'Kabupaten Sambas', 20);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (319, 'Kabupaten Sanggau', 20);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (320, 'Kabupaten Sekadau', 20);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (321, 'Kabupaten Sintang', 20);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (322, 'Kota Pontianak', 20);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (323, 'Kota Singkawang', 20);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (324, 'Kabupaten Barito Selatan', 21);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (325, 'Kabupaten Barito Timur', 21);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (326, 'Kabupaten Barito Utara', 21);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (327, 'Kabupaten Gunung Mas', 21);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (328, 'Kabupaten Kapuas', 21);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (329, 'Kabupaten Katingan', 21);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (330, 'Kabupaten Kotawaringin Barat', 21);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (331, 'Kabupaten Kotawaringin Timur', 21);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (332, 'Kabupaten Lamandau', 21);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (333, 'Kabupaten Murung Raya', 21);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (334, 'Kabupaten Pulang Pisau', 21);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (335, 'Kabupaten Seruyan', 21);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (336, 'Kabupaten Sukamara', 21);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (337, 'Kota Palangkaraya', 21);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (338, 'Kabupaten Balangan', 22);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (339, 'Kabupaten Banjar', 22);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (340, 'Kabupaten Barito Kuala', 22);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (341, 'Kabupaten Hulu Sungai Selatan', 22);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (342, 'Kabupaten Hulu Sungai Tengah', 22);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (343, 'Kabupaten Hulu Sungai Utara', 22);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (344, 'Kabupaten Kota Baru', 22);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (345, 'Kabupaten Tabalong', 22);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (346, 'Kabupaten Tanah Bumbu', 22);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (347, 'Kabupaten Tanah Laut', 22);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (348, 'Kabupaten Tapin', 22);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (349, 'Kota Banjar Baru', 22);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (350, 'Kota Banjarmasin', 22);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (351, 'Kabupaten Berau', 23);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (352, 'Kabupaten Bulongan', 23);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (353, 'Kabupaten Kutai Barat', 23);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (354, 'Kabupaten Kutai Kartanegara', 23);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (355, 'Kabupaten Kutai Timur', 23);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (356, 'Kabupaten Malinau', 23);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (357, 'Kabupaten Nunukan', 23);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (358, 'Kabupaten Paser', 23);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (359, 'Kabupaten Penajam Paser Utara', 23);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (360, 'Kabupaten Tana Tidung', 23);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (361, 'Kota Balikpapan', 23);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (362, 'Kota Bontang', 23);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (363, 'Kota Samarinda', 23);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (364, 'Kota Tarakan', 23);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (365, 'Kabupaten Boalemo', 24);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (366, 'Kabupaten Bone Bolango', 24);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (367, 'Kabupaten Gorontalo', 24);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (368, 'Kabupaten Gorontalo Utara', 24);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (369, 'Kabupaten Pohuwato', 24);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (370, 'Kota Gorontalo', 24);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (371, 'Kabupaten Bantaeng', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (372, 'Kabupaten Barru', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (373, 'Kabupaten Bone', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (374, 'Kabupaten Bulukumba', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (375, 'Kabupaten Enrekang', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (376, 'Kabupaten Gowa', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (377, 'Kabupaten Jeneponto', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (378, 'Kabupaten Luwu', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (379, 'Kabupaten Luwu Timur', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (380, 'Kabupaten Luwu Utara', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (381, 'Kabupaten Maros', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (382, 'Kabupaten Pangkajene Kepulauan', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (383, 'Kabupaten Pinrang', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (384, 'Kabupaten Selayar', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (385, 'Kabupaten Sidenreng Rappang', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (386, 'Kabupaten Sinjai', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (387, 'Kabupaten Soppeng', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (388, 'Kabupaten Takalar', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (389, 'Kabupaten Tana Toraja', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (390, 'Kabupaten Toraja Utara', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (391, 'Kabupaten Wajo', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (392, 'Kota Makassar', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (393, 'Kota Palopo', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (394, 'Kota Pare-pare', 25);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (395, 'Kabupaten Bombana', 26);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (396, 'Kabupaten Buton', 26);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (397, 'Kabupaten Buton Utara', 26);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (398, 'Kabupaten Kolaka', 26);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (399, 'Kabupaten Kolaka Utara', 26);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (400, 'Kabupaten Konawe', 26);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (401, 'Kabupaten Konawe Selatan', 26);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (402, 'Kabupaten Konawe Utara', 26);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (403, 'Kabupaten Muna', 26);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (404, 'Kabupaten Wakatobi', 26);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (405, 'Kota Bau-bau', 26);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (406, 'Kota Kendari', 26);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (407, 'Kabupaten Banggai', 27);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (408, 'Kabupaten Banggai Kepulauan', 27);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (409, 'Kabupaten Buol', 27);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (410, 'Kabupaten Donggala', 27);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (411, 'Kabupaten Morowali', 27);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (412, 'Kabupaten Parigi Moutong', 27);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (413, 'Kabupaten Poso', 27);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (414, 'Kabupaten Sigi', 27);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (415, 'Kabupaten Tojo Una-Una', 27);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (416, 'Kabupaten Toli Toli', 27);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (417, 'Kota Palu', 27);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (418, 'Kabupaten Bolaang Mangondow', 28);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (419, 'Kabupaten Bolaang Mangondow Selatan', 28);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (420, 'Kabupaten Bolaang Mangondow Timur', 28);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (421, 'Kabupaten Bolaang Mangondow Utara', 28);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (422, 'Kabupaten Kepulauan Sangihe', 28);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (423, 'Kabupaten Kepulauan Siau Tagulandang Bia', 28);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (424, 'Kabupaten Kepulauan Talaud', 28);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (425, 'Kabupaten Minahasa', 28);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (426, 'Kabupaten Minahasa Selatan', 28);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (427, 'Kabupaten Minahasa Tenggara', 28);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (428, 'Kabupaten Minahasa Utara', 28);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (429, 'Kota Bitung', 28);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (430, 'Kota Kotamobagu', 28);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (431, 'Kota Manado', 28);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (432, 'Kota Tomohon', 28);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (433, 'Kabupaten Majene', 29);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (434, 'Kabupaten Mamasa', 29);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (435, 'Kabupaten Mamuju', 29);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (436, 'Kabupaten Mamuju Utara', 29);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (437, 'Kabupaten Polewali Mandar', 29);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (438, 'Kabupaten Buru', 30);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (439, 'Kabupaten Buru Selatan', 30);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (440, 'Kabupaten Kepulauan Aru', 30);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (441, 'Kabupaten Maluku Barat Daya', 30);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (442, 'Kabupaten Maluku Tengah', 30);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (443, 'Kabupaten Maluku Tenggara', 30);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (444, 'Kabupaten Maluku Tenggara Barat', 30);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (445, 'Kabupaten Seram Bagian Barat', 30);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (446, 'Kabupaten Seram Bagian Timur', 30);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (447, 'Kota Ambon', 30);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (448, 'Kota Tual', 30);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (449, 'Kabupaten Halmahera Barat', 31);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (450, 'Kabupaten Halmahera Selatan', 31);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (451, 'Kabupaten Halmahera Tengah', 31);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (452, 'Kabupaten Halmahera Timur', 31);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (453, 'Kabupaten Halmahera Utara', 31);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (454, 'Kabupaten Kepulauan Sula', 31);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (455, 'Kabupaten Pulau Morotai', 31);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (456, 'Kota Ternate', 31);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (457, 'Kota Tidore Kepulauan', 31);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (458, 'Kabupaten Fakfak', 32);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (459, 'Kabupaten Kaimana', 32);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (460, 'Kabupaten Manokwari', 32);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (461, 'Kabupaten Maybrat', 32);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (462, 'Kabupaten Raja Ampat', 32);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (463, 'Kabupaten Sorong', 32);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (464, 'Kabupaten Sorong Selatan', 32);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (465, 'Kabupaten Tambrauw', 32);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (466, 'Kabupaten Teluk Bintuni', 32);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (467, 'Kabupaten Teluk Wondama', 32);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (468, 'Kota Sorong', 32);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (469, 'Kabupaten Merauke', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (470, 'Kabupaten Jayawijaya', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (471, 'Kabupaten Nabire', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (472, 'Kabupaten Kepulauan Yapen', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (473, 'Kabupaten Biak Numfor', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (474, 'Kabupaten Paniai', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (475, 'Kabupaten Puncak Jaya', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (476, 'Kabupaten Mimika', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (477, 'Kabupaten Boven Digoel', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (478, 'Kabupaten Mappi', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (479, 'Kabupaten Asmat', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (480, 'Kabupaten Yahukimo', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (481, 'Kabupaten Pegunungan Bintang', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (482, 'Kabupaten Tolikara', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (483, 'Kabupaten Sarmi', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (484, 'Kabupaten Keerom', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (485, 'Kabupaten Waropen', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (486, 'Kabupaten Jayapura', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (487, 'Kabupaten Deiyai', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (488, 'Kabupaten Dogiyai', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (489, 'Kabupaten Intan Jaya', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (490, 'Kabupaten Lanny Jaya', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (491, 'Kabupaten Mamberamo Raya', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (492, 'Kabupaten Mamberamo Tengah', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (493, 'Kabupaten Nduga', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (494, 'Kabupaten Puncak', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (495, 'Kabupaten Supiori', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (496, 'Kabupaten Yalimo', 33);
INSERT INTO master_city (`city_id`, `city_name`, `city_state_id`) VALUES (497, 'Kota Jayapura', 33);


#
# TABLE STRUCTURE FOR: master_country
#

DROP TABLE IF EXISTS master_country;

CREATE TABLE `master_country` (
  `country_id` int(11) NOT NULL AUTO_INCREMENT,
  `country_name` varchar(100) NOT NULL,
  PRIMARY KEY (`country_id`)
) ENGINE=MyISAM AUTO_INCREMENT=254 DEFAULT CHARSET=latin1;

INSERT INTO master_country (`country_id`, `country_name`) VALUES (1, 'Afghanistan');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (2, 'Akrotiri');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (3, 'Albania');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (4, 'Algeria');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (5, 'American Samoa');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (6, 'Andorra');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (7, 'Angola');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (8, 'Anguilla');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (9, 'Antigua and Barbuda');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (10, 'Argentina');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (11, 'Armenia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (12, 'Aruba');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (13, 'Ashmore and Cartier Islands');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (14, 'Australia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (15, 'Austria');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (16, 'Azerbaijan');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (17, 'Bahamas');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (18, 'Bahrain');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (19, 'Baker Island');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (20, 'Bangladesh');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (21, 'Barbados');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (22, 'Belarus');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (23, 'Belgium');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (24, 'Belize');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (25, 'Benin');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (26, 'Bermuda');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (27, 'Bhutan');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (28, 'Bolivia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (29, 'Bosnia and Herzegovina');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (30, 'Botswana');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (31, 'Bouvet Island');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (32, 'Brazil');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (33, 'British Indian Ocean Territory');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (34, 'British Virgin Islands');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (35, 'Brunei');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (36, 'Bulgaria');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (37, 'Burkina Faso');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (38, 'Burma');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (39, 'Burundi');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (40, 'Cambodia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (41, 'Cameroon');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (42, 'Canada');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (43, 'Cape Verde');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (44, 'Cayman Islands');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (45, 'Central African Republic');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (46, 'Chad');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (47, 'Chile');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (48, 'China');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (49, 'Christmas Island');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (50, 'Clipperton Island');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (51, 'Cocos (Keeling) Islands');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (52, 'Colombia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (53, 'Comoros');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (54, 'Congo');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (55, 'Cook Islands');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (56, 'Coral Sea Islands');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (57, 'Costa Rica');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (58, 'Cote d Ivoire');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (59, 'Croatia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (60, 'Cuba');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (61, 'Cyprus');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (62, 'Czech Republic');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (63, 'Denmark');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (64, 'Dhekelia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (65, 'Djibouti');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (66, 'Dominica');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (67, 'Dominican Republic');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (68, 'Ecuador flag');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (69, 'Egypt');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (70, 'El Salvador');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (71, 'Equatorial Guinea');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (72, 'Eritrea');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (73, 'Estonia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (74, 'Ethiopia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (75, 'European Union');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (76, 'Falkland Islands flag');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (77, 'Faroe Islands');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (78, 'Fiji');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (79, 'Finland');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (80, 'France');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (81, 'French Polynesia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (82, 'French Southern and Antarctic Lands');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (83, 'Gabon');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (84, 'Gambia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (85, 'Georgia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (86, 'Germany');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (87, 'Ghana');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (88, 'Gibraltar');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (89, 'Greece');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (90, 'Greenland');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (91, 'Grenada');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (92, 'Guam');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (93, 'Guatemala');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (94, 'Guernsey');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (95, 'Guinea Bissau');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (96, 'Guinea');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (97, 'Guyana');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (98, 'Haiti');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (99, 'Heard Island and McDonald Islands');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (100, 'Holy See');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (101, 'Honduras');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (102, 'Hong Kong');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (103, 'Howland Island');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (104, 'Hungary');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (105, 'Iceland');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (106, 'India');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (107, 'Indonesia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (108, 'Iran');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (109, 'Iraq');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (110, 'Ireland');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (111, 'Isle of Man');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (112, 'Israel');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (113, 'Italy');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (114, 'Jamaica flag');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (115, 'Jan Mayen');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (116, 'Japan');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (117, 'Jarvis Island');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (118, 'Jersey');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (119, 'Johnston Atoll');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (120, 'Jordan');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (121, 'Kazakhstan');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (122, 'Kenya');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (123, 'Kingman Reef');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (124, 'Kiribati');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (125, 'Kuwait');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (126, 'Kyrgyzstan');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (127, 'Laos');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (128, 'Latvia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (129, 'Lebanon');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (130, 'Lesotho');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (131, 'Liberia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (132, 'Libya');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (133, 'Liechtenstein');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (134, 'Lithuania');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (135, 'Luxembourg');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (136, 'Macau');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (137, 'Macedonia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (138, 'Madagascar');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (139, 'Malawi');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (140, 'Malaysia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (141, 'Maldives');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (142, 'Mali');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (143, 'Malta');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (144, 'Marshall Islands');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (145, 'Mauritania');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (146, 'Mauritius');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (147, 'Mayotte');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (148, 'Mexico');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (149, 'Micronesia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (150, 'Midway Islands');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (151, 'Moldova');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (152, 'Monaco');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (153, 'Mongolia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (154, 'Montenegro');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (155, 'Montserrat');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (156, 'Morocco');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (157, 'Mozambique');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (158, 'Namibia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (159, 'Nauru');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (160, 'Navassa Island');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (161, 'Nepal');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (162, 'Netherlands Antilles');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (163, 'Netherlands');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (164, 'New Caledonia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (165, 'New Zealand');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (166, 'Nicaragua');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (167, 'Niger');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (168, 'Nigeria');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (169, 'Niue');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (170, 'Norfolk Island');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (171, 'North Korea');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (172, 'Northern Mariana Islands');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (173, 'Norway');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (174, 'Oman');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (175, 'Pakistan');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (176, 'Palau');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (177, 'Palmyra Atoll');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (178, 'Panama');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (179, 'Papua New Guinea');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (180, 'Paraguay');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (181, 'Peru');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (182, 'Philippines');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (183, 'Pitcairn Islands');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (184, 'Poland');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (185, 'Portugal');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (186, 'Puerto Rico');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (187, 'Qatar');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (188, 'Romania');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (189, 'Russia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (190, 'Rwanda');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (191, 'Saint Barthelemy');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (192, 'Saint Helena');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (193, 'Saint Kitts and Nevis');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (194, 'Saint Lucia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (195, 'Saint Martin');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (196, 'Saint Pierre and Miquelon');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (197, 'Saint Vincent and the Grenadines');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (198, 'Samoa');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (199, 'San Marino');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (200, 'Sao Tome and Principe');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (201, 'Saudi Arabia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (202, 'Senegal');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (203, 'Serbia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (204, 'Seychelles');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (205, 'Sierra Leone');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (206, 'Singapore');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (207, 'Slovakia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (208, 'Slovenia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (209, 'Solomon Islands');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (210, 'Somalia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (211, 'South Africa');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (212, 'South Georgia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (213, 'South Korea');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (214, 'Spain');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (215, 'Sri Lanka');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (216, 'Sudan');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (217, 'Suriname');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (218, 'Svalbard');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (219, 'Swaziland');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (220, 'Sweden');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (221, 'Switzerland');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (222, 'Syria');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (223, 'Taiwan');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (224, 'Tajikistan');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (225, 'Tanzania');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (226, 'Thailand');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (227, 'Timor Leste');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (228, 'Togo');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (229, 'Tokelau');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (230, 'Tonga');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (231, 'Trinidad and Tobago');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (232, 'Tunisia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (233, 'Turkey');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (234, 'Turkmenistan');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (235, 'Turks and Caicos Islands');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (236, 'Tuvalu');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (237, 'Uganda');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (238, 'Ukraine');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (239, 'United Arab Emirates');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (240, 'United Kingdom');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (241, 'United States');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (242, 'Uruguay');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (243, 'US Pacific Island Wildlife Refuges');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (244, 'Uzbekistan');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (245, 'Vanuatu');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (246, 'Venezuela');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (247, 'Vietnam');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (248, 'Virgin Islands');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (249, 'Wake Island');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (250, 'Wallis and Futuna');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (251, 'Yemen');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (252, 'Zambia');
INSERT INTO master_country (`country_id`, `country_name`) VALUES (253, 'Zimbabwe');


#
# TABLE STRUCTURE FOR: master_state
#

DROP TABLE IF EXISTS master_state;

CREATE TABLE `master_state` (
  `state_id` int(3) NOT NULL AUTO_INCREMENT,
  `state_name` varchar(30) NOT NULL,
  `state_country_id` int(11) NOT NULL,
  PRIMARY KEY (`state_id`)
) ENGINE=MyISAM AUTO_INCREMENT=35 DEFAULT CHARSET=utf8;

INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (1, 'Nanggroe Aceh Darussalam', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (2, 'Sumatera Utara', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (3, 'Sumatera Barat', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (4, 'Riau', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (5, 'Kepulauan Riau', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (6, 'Kepulauan Bangka-Belitung', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (7, 'Jambi', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (8, 'Bengkulu', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (9, 'Sumatera Selatan', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (10, 'Lampung', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (11, 'Banten', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (12, 'DKI Jakarta', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (13, 'Jawa Barat', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (14, 'Jawa Tengah', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (15, 'Daerah Istimewa Yogyakarta  ', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (16, 'Jawa Timur', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (17, 'Bali', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (18, 'Nusa Tenggara Barat', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (19, 'Nusa Tenggara Timur', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (20, 'Kalimantan Barat', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (21, 'Kalimantan Tengah', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (22, 'Kalimantan Selatan', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (23, 'Kalimantan Timur', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (24, 'Gorontalo', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (25, 'Sulawesi Selatan', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (26, 'Sulawesi Tenggara', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (27, 'Sulawesi Tengah', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (28, 'Sulawesi Utara', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (29, 'Sulawesi Barat', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (30, 'Maluku', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (31, 'Maluku Utara', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (32, 'Papua Barat', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (33, 'Papua', 107);
INSERT INTO master_state (`state_id`, `state_name`, `state_country_id`) VALUES (34, 'afgan syahreza', 1);


#
# TABLE STRUCTURE FOR: t_map
#

DROP TABLE IF EXISTS t_map;

CREATE TABLE `t_map` (
  `id_map` int(5) NOT NULL AUTO_INCREMENT,
  `lat` text NOT NULL,
  `long` text NOT NULL,
  `nama_lokasi` text NOT NULL,
  PRIMARY KEY (`id_map`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=latin1;

INSERT INTO t_map (`id_map`, `lat`, `long`, `nama_lokasi`) VALUES (1, '-6.294387', '106.845359', ' Jl. Raya Pasar Minggu & Jl. Raya Tanjung Barat');


